### PR TITLE
Run the project check on every push and pull request

### PR DESCRIPTION
**Pull request by schalermthai**
## Problem

The repository has only a publish workflow. It runs on a release or a manual trigger.

Nothing runs `npm run check` on a push or a pull request. Two merged pull requests shipped breaks that no gate caught:

- PR #4 added a workspace fixture without updating `package-lock.json`. `npm ci` then failed.
- PR #7 added the `redproof/command` subpath without a `tsconfig.json` path entry. `npm run check` then failed on a clean checkout with TS2307.

Both were found by hand. Both would have failed the release.

## Fix

Add `.github/workflows/ci.yml`. It runs on every push to `main` and on every pull request.

Steps: `npm ci`, `npm run check`, `npm run build`, `npm run verify:package`.

- `npm ci` proves `package.json` and `package-lock.json` still agree. This catches the PR #4 class.
- `npm run check` runs `typecheck` before any build exists. This catches the PR #7 class.
- The build is explicit before `verify:package`, so package verification never reads a stale `dist`.
- Node 24, the version `engines` requires.
- Concurrency cancels a run that a newer push replaces.

## Verification

Timed locally on a clean checkout: `npm run check` 10.5s, `npm run verify:package` 18.6s.

The red proof for this gate is recorded in the comments below.

### CODE REVIEW

**Comment by schalermthai** [comment]
## Red proof

A gate that can only print success looks exactly like a gate that works. So each step was broken on this branch and confirmed red on a real run, then restored.

| # | Break | Step that failed | What the log said |
|---|---|---|---|
| 1 | Removed the `redproof/command` path from `tsconfig.json` | Run the full project check | `TS2307: Cannot find module 'redproof/command'`, exit code 2 |
| 2 | Added a workspace fixture without updating `package-lock.json` | Install dependencies | `EUSAGE ... Missing: redproof-ci-probe@ from lock file`, exit code 1 |
| 3 | Removed the `./command` entry from the package `exports` | Run the full project check | `ERR_PACKAGE_PATH_NOT_EXPORTED: Package subpath './command' is not defined`, exit code 1 |
| 4 | Added a relative `docs/` link to `README.md` | Verify the packages a consumer would install | `FAIL  redproof: README has no links to unshipped relative docs`, exit code 1 |

Breaks 1 and 2 are the two bugs that reached `main` in #7 and #4. This workflow catches both.

Break 4 was needed because breaks 1 to 3 all stop the run earlier. It proves the last step is reachable and can fail on its own.

Green runs before break 1 and after the restore: `Check and verify: COMPLETED SUCCESS`.

### Not proven

`Build the production artifact` was never the first step to fail. `npm run check` builds first through `pretest`, so a build error always fails the earlier step. The step is kept because it guarantees `verify:package` reads a fresh `dist`, never a stale one.
